#!perl
use strict;
use warnings;

package rami;

# PODNAME: rami
# ABSTRACT: automate merging to an arbitrary number of branches

# To invoke this script from the dev environment, use:
#   perl -Ilib script\rami
# For example:
#   perl -Ilib script\rami -c 84987 

use SVN::Rami;

# TODO: parse equals sign: --load-repo-config-from-svn-url=http://...
my $load_config_from_SVN_arg = '--load-repo-config-from-svn-url';

my $command = shift;   # Usually this is '-c'
my $source_revision = shift;
my $valid_command = ($command eq '-c' or $command eq $load_config_from_SVN_arg);
if ( not $source_revision or not $valid_command ) {
	print "Usage: $0 -c <revision_number>\n";
	print "or: $0 $load_config_from_SVN_arg <SVN-URL>\n";
	exit 1;
}

if ($command eq $load_config_from_SVN_arg) {
	SVN::Rami::load_config_from_SVN_url($source_revision);
} else {
	# The usual case.
	SVN::Rami::rami_main($source_revision);
}
